# Use an official Node.js runtime as the base image
FROM node:14 as build-stage

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy app files to the container
COPY . .

# Build the React app
RUN npm run build

# Use a lightweight nginx image to serve the React app
FROM nginx:alpine
COPY --from=build-stage /app/build /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
